### ISSUE TITLE
Jak to można uruchomić na raspberry pi? 

### ISSUE THREAD

**Issue by djdandi** [prokulski/Dane-IMGW#1]
Witam czy można to uruchomić na raspberry pi?
Co jest mi potrzebne? i jak to odpalić?

**Comment by prokulski** [comment]
Malina to w sumie Linux, więc gdzieś tym http://prokulski.net/index.php/2018/06/14/serwer-vps-dla-r-python/ tropem bym postawił środowisko z R, a potem to albo konsola albo cron
