### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by pawelm7** [prokulski/Dane-IMGW#2]
Cześć, dziękuje bardzo za udostępnienie Twoich skryptów pogodowych. Jestem pod wrażeniem Twojej pracy:) 
 Niestety u mnie nie zadziało pobranie plików ze strony IMGW. Czyżby coś zmienili czy to może wina mojego oprogramowania ew. dostępu do internetu (firewall etc.)? Dostaje zwrotny komunikat:
Error during wrapup: Failed to connect to dane.imgw.pl port 443: Connection refused

Z góry dziękuję za pomoc
Paweł

**Comment by prokulski** [comment]
Zapewne gdzieś po drodze coś blikuje ruch. Wszystko zaczyna się od ścieżki https://dane.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/terminowe/klimat/ i sięga wgłąb katalogów. U mnie ta początkowa ścieżka się otwiera, nie widzę żadnych problemów.
